# Generated by Django 3.1.6 on 2021-03-26 12:50

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Просмотры страницы',
                'verbose_name_plural': 'Просмотры страницы',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок поста')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок поста')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок поста')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Заголовок поста')),
                ('slug', models.SlugField(unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контентная часть')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контентная часть')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контентная часть')),
                ('description_kk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контентная часть')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время')),
                ('author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='PostCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категорий')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок вопроса')),
                ('description', models.TextField(verbose_name='Описание вопроса')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Questions/Posters/', verbose_name='изо')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название цитаты')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название цитаты')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название цитаты')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Название цитаты')),
                ('description', models.TextField(verbose_name='Описание цитаты')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание цитаты')),
                ('description_en', models.TextField(null=True, verbose_name='Описание цитаты')),
                ('description_kk', models.TextField(null=True, verbose_name='Описание цитаты')),
                ('author', models.CharField(max_length=255, verbose_name='Автор Цитаты')),
                ('author_ru', models.CharField(max_length=255, null=True, verbose_name='Автор Цитаты')),
                ('author_en', models.CharField(max_length=255, null=True, verbose_name='Автор Цитаты')),
                ('author_kk', models.CharField(max_length=255, null=True, verbose_name='Автор Цитаты')),
                ('img', models.ImageField(upload_to='Quete/Posters/', verbose_name='изо')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
            },
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Posts/Images', verbose_name='Изображения')),
                ('post', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='post_img', to='news.post')),
            ],
            options={
                'verbose_name': 'Фотография поста',
                'verbose_name_plural': 'Фотографий поста',
            },
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_com', to='news.post')),
            ],
            options={
                'verbose_name': 'Коментарий поста',
                'verbose_name_plural': 'Коментарий поста',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.postcategories'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news.post')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
    ]
