# Generated by Django 3.1.6 on 2021-06-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое'),
        ),
        migrations.AddField(
            model_name='post',
            name='short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое'),
        ),
        migrations.AddField(
            model_name='post',
            name='short_description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое'),
        ),
        migrations.AddField(
            model_name='post',
            name='short_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое'),
        ),
    ]
