# Generated by Django 3.1.6 on 2021-03-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categoryp',
        ),
    ]
