# Generated by Django 3.1.5 on 2021-02-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_quote_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='img',
            field=models.ImageField(upload_to='Quete/Posters/', verbose_name='изо'),
        ),
    ]
