# Generated by Django 3.1.6 on 2021-03-26 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_post_categoryp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoryp',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.postcategories'),
        ),
    ]
