# Generated by Django 3.1.6 on 2021-06-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210622_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='slides',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
