# Generated by Django 3.1.6 on 2021-04-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTitle', models.CharField(max_length=255, verbose_name='Субтитл')),
                ('title', models.CharField(max_length=255, verbose_name='Загаловка')),
                ('link1', models.CharField(max_length=255, verbose_name='первая ссылка')),
                ('link2', models.CharField(max_length=255, verbose_name='вторая ссылка')),
                ('img', models.ImageField(upload_to='Slides/')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
