# Generated by Django 3.1.6 on 2021-03-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_categoryp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.postcategories'),
        ),
    ]
