# Generated by Django 3.1.6 on 2021-04-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='slides',
            name='btn',
            field=models.CharField(default=1, max_length=255, verbose_name='Названия первой кнопки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slides',
            name='btn2',
            field=models.CharField(default=1, max_length=255, verbose_name='Названия второй кнопки'),
            preserve_default=False,
        ),
    ]
