# Generated by Django 3.1.6 on 2021-04-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210426_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='slides',
            name='btn2_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Названия второй кнопки'),
        ),
        migrations.AddField(
            model_name='slides',
            name='btn2_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Названия второй кнопки'),
        ),
        migrations.AddField(
            model_name='slides',
            name='btn2_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Названия второй кнопки'),
        ),
        migrations.AddField(
            model_name='slides',
            name='btn_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Названия первой кнопки'),
        ),
        migrations.AddField(
            model_name='slides',
            name='btn_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Названия первой кнопки'),
        ),
        migrations.AddField(
            model_name='slides',
            name='btn_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Названия первой кнопки'),
        ),
        migrations.AddField(
            model_name='slides',
            name='subTitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Субтитл'),
        ),
        migrations.AddField(
            model_name='slides',
            name='subTitle_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Субтитл'),
        ),
        migrations.AddField(
            model_name='slides',
            name='subTitle_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Субтитл'),
        ),
        migrations.AddField(
            model_name='slides',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Загаловка'),
        ),
        migrations.AddField(
            model_name='slides',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Загаловка'),
        ),
        migrations.AddField(
            model_name='slides',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Загаловка'),
        ),
    ]
