# Generated by Django 3.1.6 on 2021-02-06 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210206_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 10, 15, 7, 936114), verbose_name='Время'),
        ),
    ]
