# Generated by Django 3.1.6 on 2021-02-06 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20210206_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomments',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 10, 28, 37, 773349), verbose_name='Время'),
        ),
    ]
