# Generated by Django 3.1.6 on 2021-02-11 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20210207_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 10, 31, 6, 970697), verbose_name='Время'),
        ),
    ]
