# Generated by Django 3.1.6 on 2021-02-10 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20210207_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 12, 4, 41, 868482), verbose_name='Время'),
        ),
    ]
