# Generated by Django 3.1.6 on 2021-02-11 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20210211_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Описание поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок поста'),
        ),
        migrations.AddField(
            model_name='quote',
            name='author_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Автор Цитаты'),
        ),
        migrations.AddField(
            model_name='quote',
            name='author_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Автор Цитаты'),
        ),
        migrations.AddField(
            model_name='quote',
            name='author_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Автор Цитаты'),
        ),
        migrations.AddField(
            model_name='quote',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание цитаты'),
        ),
        migrations.AddField(
            model_name='quote',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Описание цитаты'),
        ),
        migrations.AddField(
            model_name='quote',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание цитаты'),
        ),
        migrations.AddField(
            model_name='quote',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название цитаты'),
        ),
        migrations.AddField(
            model_name='quote',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название цитаты'),
        ),
        migrations.AddField(
            model_name='quote',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название цитаты'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 11, 8, 24, 660398), verbose_name='Время'),
        ),
    ]
