# Generated by Django 3.1.6 on 2021-02-11 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20210211_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AlterModelOptions(
            name='pagehit',
            options={'verbose_name': 'Просмотры страницы', 'verbose_name_plural': 'Просмотры страницы'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='postcomments',
            options={'verbose_name': 'Коментарий поста', 'verbose_name_plural': 'Коментарий поста'},
        ),
        migrations.AlterModelOptions(
            name='postimages',
            options={'verbose_name': 'Фотография поста', 'verbose_name_plural': 'Фотографий поста'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Цитата', 'verbose_name_plural': 'Цитаты'},
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 12, 21, 6, 302343), verbose_name='Время'),
        ),
    ]
