# Generated by Django 3.1.6 on 2021-02-11 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_auto_20210211_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 13, 41, 13, 581363), verbose_name='Время'),
        ),
    ]
