# Generated by Django 3.1.6 on 2021-02-11 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20210211_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 14, 11, 36, 288935), verbose_name='Время'),
        ),
    ]
