# Generated by Django 3.1.6 on 2021-02-11 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_auto_20210211_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 15, 52, 3, 477816), verbose_name='Время'),
        ),
    ]
