# Generated by Django 3.1.6 on 2021-02-11 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0036_auto_20210211_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 18, 14, 11, 914261), verbose_name='Время'),
        ),
    ]
