# Generated by Django 3.1.6 on 2021-02-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20210210_1204'),
        ('news', '0038_auto_20210211_1817'),
    ]

    operations = [
    ]
