# Generated by Django 3.1.5 on 2021-02-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Url Должность персонала'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Url персонала'),
        ),
        migrations.AlterField(
            model_name='staffcat',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Url Категория персонала'),
        ),
    ]
