# Generated by Django 3.1.6 on 2021-02-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20210202_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность персонала'),
        ),
        migrations.AddField(
            model_name='position',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность персонала'),
        ),
        migrations.AddField(
            model_name='position',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность персонала'),
        ),
        migrations.AddField(
            model_name='staff',
            name='about_en',
            field=models.TextField(null=True, verbose_name='О персонале'),
        ),
        migrations.AddField(
            model_name='staff',
            name='about_kk',
            field=models.TextField(null=True, verbose_name='О персонале'),
        ),
        migrations.AddField(
            model_name='staff',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='О персонале'),
        ),
        migrations.AddField(
            model_name='staff',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя персонала'),
        ),
        migrations.AddField(
            model_name='staff',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя персонала'),
        ),
        migrations.AddField(
            model_name='staff',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя персонала'),
        ),
        migrations.AddField(
            model_name='staffcat',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Категория персонала'),
        ),
        migrations.AddField(
            model_name='staffcat',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Категория персонала'),
        ),
        migrations.AddField(
            model_name='staffcat',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Категория персонала'),
        ),
    ]
