# Generated by Django 3.1.6 on 2021-02-12 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0015_auto_20210211_2013'),
        ('departments', '0012_auto_20210211_1108'),
        ('staff', '0004_auto_20210212_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='facult',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faculties.facult'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='educationalPrograms',
            field=models.ManyToManyField(to='departments.EducationalPrograms'),
        ),
    ]
