# Generated by Django 3.1.6 on 2021-02-12 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0012_auto_20210211_1108'),
        ('staff', '0005_auto_20210212_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='educationalPrograms',
        ),
        migrations.AddField(
            model_name='staff',
            name='educationalPrograms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departments.educationalprograms'),
            preserve_default=False,
        ),
    ]
