# Generated by Django 3.1.6 on 2021-02-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20210212_0834'),
        ('staff', '0007_auto_20210212_0838'),
    ]

    operations = [
    ]
