# Generated by Django 3.1.6 on 2021-02-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0012_auto_20210211_1108'),
        ('staff', '0008_merge_20210213_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='educationalPrograms',
            field=models.ManyToManyField(to='departments.EducationalPrograms'),
        ),
    ]
