# Generated by Django 3.1.6 on 2021-02-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0012_auto_20210211_1108'),
        ('staff', '0011_auto_20210213_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='educationalPrograms',
            field=models.ManyToManyField(blank=True, null=True, to='departments.EducationalPrograms'),
        ),
    ]
