# Generated by Django 3.1.6 on 2021-03-26 12:11

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название факультета')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название факультета')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название факультета')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Название факультета')),
                ('slug', models.SlugField(unique=True, verbose_name='Url факультета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание факультета')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание факультета')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание факультета')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Описание факультета')),
                ('photo', models.ImageField(default=0, upload_to='Facult/Posters/', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Филтрация')),
                ('title', models.CharField(max_length=255, verbose_name='Название страницы')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название страницы')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название страницы')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Название страницы')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка НУЖНО ИМЯ')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug это обычный слаг')),
                ('link', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылку на сайт')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контентная часть')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контентная часть')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контентная часть')),
                ('content_kk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контентная часть')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Page/', verbose_name='Постер страницы')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='PageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='НАзвани катоегрий')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='НАзвани катоегрий')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='НАзвани катоегрий')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='НАзвани катоегрий')),
            ],
            options={
                'verbose_name': 'Категория Страницы',
                'verbose_name_plural': 'Категорий Страницы',
            },
        ),
        migrations.CreateModel(
            name='PageImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='PageImages/', verbose_name='Фотографий страницы')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageImages', to='faculties.page')),
            ],
            options={
                'verbose_name': 'Фотограция страницы',
                'verbose_name_plural': 'Фотограций страницы',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='faculties.pagecategory'),
        ),
    ]
