# Generated by Django 3.1.5 on 2021-02-01 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название факультета')),
                ('slug', models.SlugField(verbose_name='Url факультета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание факультета')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='FacultFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Facult/Posters/', verbose_name='Изображения')),
                ('facult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculties.facult')),
            ],
        ),
    ]
