# Generated by Django 3.1.5 on 2021-02-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facult',
            name='photo',
            field=models.ImageField(default=0, upload_to='Facult/Posters/', verbose_name='Изображения'),
        ),
        migrations.DeleteModel(
            name='FacultFoto',
        ),
    ]
