# Generated by Django 3.1.6 on 2021-04-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Филтрация'),
        ),
    ]
