# Generated by Django 3.1.6 on 2021-04-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0002_pagecategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecategory',
            name='linkto',
            field=models.CharField(blank=True, default=0, max_length=255, null=True, verbose_name='Ссылка на чего либо'),
        ),
    ]
