# Generated by Django 3.1.5 on 2021-02-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0002_auto_20210201_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facult',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Url факультета'),
        ),
    ]
