# Generated by Django 3.1.6 on 2021-02-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0005_page_pageimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Контентная часть'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_kk',
            field=models.TextField(null=True, verbose_name='Контентная часть'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Контентная часть'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название страницы'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название страницы'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название страницы'),
        ),
    ]
