# Generated by Django 3.1.6 on 2021-02-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0007_auto_20210211_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
