# Generated by Django 3.1.6 on 2021-02-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0008_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(max_length=255, verbose_name='Ссылка'),
        ),
    ]
