# Generated by Django 3.1.6 on 2021-02-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0010_auto_20210211_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecategory',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
