# Generated by Django 3.1.6 on 2021-02-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0013_auto_20210211_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facult',
            name='slug',
            field=models.SlugField(verbose_name='Url факультета'),
        ),
    ]
