# Generated by Django 3.1.6 on 2021-02-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0014_auto_20210211_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facult',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Url факультета'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug это обычный слаг'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Ссылка НУЖНО ИМЯ'),
        ),
    ]
