# Generated by Django 3.1.6 on 2021-02-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0015_auto_20210211_2013'),
        ('faculties', '0012_remove_pagecategory_slug'),
    ]

    operations = [
    ]
