# Generated by Django 3.1.6 on 2021-02-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0016_merge_20210211_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facult',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Url факультета'),
        ),
    ]
