# Generated by Django 3.1.6 on 2021-02-13 08:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0016_merge_20210212_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Контентная часть'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Контентная часть'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_kk',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Контентная часть'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Контентная часть'),
        ),
    ]
