# Generated by Django 3.1.6 on 2021-02-13 08:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0017_auto_20210213_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Контентная часть'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Контентная часть'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Контентная часть'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Контентная часть'),
        ),
    ]
