# Generated by Django 3.1.6 on 2021-02-17 18:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0019_auto_20210217_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контентная часть'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контентная часть'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контентная часть'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контентная часть'),
        ),
    ]
