# Generated by Django 3.1.6 on 2021-03-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0020_auto_20210217_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылку на сайт'),
        ),
    ]
