# Generated by Django 3.1.6 on 2021-03-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0021_page_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Филтрация'),
        ),
    ]
