# Generated by Django 3.1.6 on 2021-04-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='order',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
