# Generated by Django 3.1.6 on 2021-04-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_widget_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='iic_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
