# Generated by Django 3.2.1 on 2021-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('shifr_name', models.CharField(max_length=255, verbose_name='Мамандық шифры, атауы')),
                ('course', models.SmallIntegerField(default=1, max_length=4, verbose_name='Курс')),
                ('top', models.CharField(max_length=12, verbose_name='Топ')),
                ('phone', models.CharField(max_length=11, verbose_name='Тел номері')),
                ('rejim', models.CharField(choices=[(1, 'Қашықтан'), (2, 'Күндізгі')], max_length=255, verbose_name='Оқу режимы')),
                ('language', models.CharField(choices=[(1, 'Қазақ'), (2, 'Орыс')], max_length=255, verbose_name='Оқу тілі')),
            ],
        ),
    ]
