# Generated by Django 3.2.1 on 2021-08-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeuniver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='genereted_file',
            field=models.FileField(blank=True, null=True, upload_to='genereted/'),
        ),
    ]
