# Generated by Django 3.2.1 on 2021-08-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeuniver', '0002_zayavka_genereted_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zayavka',
            options={'verbose_name': 'Заявку', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='zayavka',
            name='created_at',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
