# Generated by Django 3.2.1 on 2021-08-20 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('changeuniver', '0003_auto_20210820_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shifr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Мамандық шифры, атауы')),
            ],
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='shifr_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changeuniver.shifr', verbose_name='Мамандық шифры, атауы'),
        ),
    ]
