# Generated by Django 3.2.1 on 2021-08-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeuniver', '0004_auto_20210820_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shifr',
            options={'verbose_name': 'Шифр', 'verbose_name_plural': 'Шифры'},
        ),
        migrations.RemoveField(
            model_name='zayavka',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='language',
            field=models.CharField(choices=[('қазақ', 'қазақ'), ('орыс', 'орыс')], max_length=255, verbose_name='Оқу тілі'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='rejim',
            field=models.CharField(choices=[('қашықтан', 'қашықтан'), ('күндізгі', 'күндізгі')], max_length=255, verbose_name='Оқу режимы'),
        ),
    ]
