# Generated by Django 3.1.6 on 2021-02-17 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0020_auto_20210217_1814'),
        ('swiupanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='faculties.page', verbose_name='Страница которому нужно подключиться'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget', to='swiupanel.widgettype', verbose_name='Тип виджета которому нужно подключиться'),
        ),
        migrations.AlterField(
            model_name='widgetitems',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgetitems', to='swiupanel.widget', verbose_name='Виджет'),
        ),
    ]
