# Generated by Django 3.1.6 on 2021-03-26 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок поста')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок поста')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок поста')),
                ('title_kk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок поста')),
                ('slug', models.SlugField(unique=True, verbose_name='Url факультета')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('short_description_ru', models.TextField(null=True, verbose_name='Краткое описание')),
                ('short_description_en', models.TextField(null=True, verbose_name='Краткое описание')),
                ('short_description_kk', models.TextField(null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Полная описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Полная описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Полная описание')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Полная описание')),
            ],
            options={
                'verbose_name': 'Деятельность кафедра',
                'verbose_name_plural': 'Деятельность кафедры',
            },
        ),
        migrations.CreateModel(
            name='ActivityDepartmentCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовк категорий')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовк категорий')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Заголовк категорий')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Заголовк категорий')),
                ('slug', models.SlugField(unique=True, verbose_name='Url категорий')),
            ],
            options={
                'verbose_name': 'Категория деятельности кафедра',
                'verbose_name_plural': 'Категория деятельности кафедры',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кафедры')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название кафедры')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название кафедры')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Название кафедры')),
                ('slug', models.SlugField(unique=True, verbose_name='Url факультета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание кафедра')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание кафедра')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание кафедра')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Описание кафедра')),
                ('img', models.ImageField(upload_to='Department/Posters/', verbose_name='Изображения')),
                ('facult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculties.facult')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='EducationalProgramsCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название Категорий')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название Категорий')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название Категорий')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Название Категорий')),
            ],
            options={
                'verbose_name': 'Категория оброзовательных программам',
                'verbose_name_plural': 'Категорий оброзовательных программам',
            },
        ),
        migrations.CreateModel(
            name='EducationalPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кафедры')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название кафедры')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название кафедры')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Название кафедры')),
                ('slug', models.SlugField(unique=True, verbose_name='Url факультета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание кафедра')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание кафедра')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание кафедра')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Описание кафедра')),
                ('img', models.ImageField(upload_to='Edu/Posters/', verbose_name='Изображения')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.educationalprogramscat')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('facult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculties.facult')),
            ],
            options={
                'verbose_name': 'Оброзовательные программа',
                'verbose_name_plural': 'Оброзовательные программы',
            },
        ),
        migrations.CreateModel(
            name='ActivityDepartmentFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Department/Activity/', verbose_name='Изображения')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activityDepartmentFoto', to='departments.activitydepartment')),
            ],
            options={
                'verbose_name': 'Деятельность кафедры фото',
                'verbose_name_plural': 'Деятельность кафедры фотки',
            },
        ),
        migrations.AddField(
            model_name='activitydepartment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.activitydepartmentcat'),
        ),
        migrations.AddField(
            model_name='activitydepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
    ]
