# Generated by Django 3.1.5 on 2021-02-01 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок поста')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Полная описание')),
            ],
            options={
                'verbose_name': 'Деятельность кафедра',
                'verbose_name_plural': 'Деятельность кафедры',
            },
        ),
        migrations.CreateModel(
            name='EducationalPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кафедры')),
                ('slug', models.SlugField(verbose_name='Url факультета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание кафедра')),
                ('img', models.ImageField(upload_to='Edu/Posters/', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Оброзовательные программа',
                'verbose_name_plural': 'Оброзовательные программы',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кафедры')),
                ('slug', models.SlugField(verbose_name='Url факультета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание кафедра')),
                ('img', models.ImageField(upload_to='Department/Posters/', verbose_name='Изображения')),
                ('facult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculties.facult')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='ActivityDepartmentFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Department/Activity/', verbose_name='Изображения')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.activitydepartment')),
            ],
            options={
                'verbose_name': 'Деятельность кафедры фото',
                'verbose_name_plural': 'Деятельность кафедры фотки',
            },
        ),
    ]
