# Generated by Django 3.1.6 on 2021-04-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0002_pagecategory_order'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='facult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='faculties.facult'),
        ),
        migrations.AlterField(
            model_name='educationalprograms',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edupros', to='departments.department'),
        ),
    ]
