# Generated by Django 3.1.5 on 2021-02-01 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20210201_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDepartmentCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовк категорий')),
                ('slug', models.SlugField(verbose_name='Url категорий')),
            ],
        ),
        migrations.AddField(
            model_name='activitydepartment',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='departments.activitydepartmentcat'),
        ),
    ]
