# Generated by Django 3.1.5 on 2021-02-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20210201_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydepartment',
            name='slug',
            field=models.SlugField(default=0, verbose_name='Url факультета'),
        ),
    ]
