# Generated by Django 3.1.5 on 2021-02-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_activitydepartment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydepartment',
            name='slug',
            field=models.SlugField(verbose_name='Url факультета'),
        ),
    ]
