# Generated by Django 3.1.5 on 2021-02-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_activitydepartment_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitydepartmentcat',
            options={'verbose_name': 'Категория деятельности кафедра', 'verbose_name_plural': 'Категория деятельности кафедры'},
        ),
        migrations.RemoveField(
            model_name='activitydepartmentcat',
            name='department',
        ),
    ]
