# Generated by Django 3.1.5 on 2021-02-01 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0008_auto_20210201_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalProgramsCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название Категорий')),
            ],
        ),
        migrations.AddField(
            model_name='educationalprograms',
            name='cat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='departments.educationalprogramscat'),
        ),
    ]
