# Generated by Django 3.1.5 on 2021-02-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0009_auto_20210202_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydepartment',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Url факультета'),
        ),
        migrations.AlterField(
            model_name='activitydepartmentcat',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Url категорий'),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Url факультета'),
        ),
        migrations.AlterField(
            model_name='educationalprograms',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Url факультета'),
        ),
    ]
