# Generated by Django 3.1.5 on 2021-02-02 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0010_auto_20210202_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydepartmentfoto',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activityDepartmentFoto', to='departments.activitydepartment'),
        ),
    ]
