# Generated by Django 3.1.6 on 2021-02-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0011_auto_20210202_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalprogramscat',
            options={'verbose_name': 'Категория оброзовательных программам', 'verbose_name_plural': 'Категорий оброзовательных программам'},
        ),
        migrations.AddField(
            model_name='activitydepartment',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Полная описание'),
        ),
        migrations.AddField(
            model_name='activitydepartment',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Полная описание'),
        ),
        migrations.AddField(
            model_name='activitydepartment',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Полная описание'),
        ),
        migrations.AddField(
            model_name='activitydepartment',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='activitydepartment',
            name='short_description_kk',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='activitydepartment',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='activitydepartment',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок поста'),
        ),
        migrations.AddField(
            model_name='activitydepartment',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок поста'),
        ),
        migrations.AddField(
            model_name='activitydepartment',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок поста'),
        ),
        migrations.AddField(
            model_name='activitydepartmentcat',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовк категорий'),
        ),
        migrations.AddField(
            model_name='activitydepartmentcat',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовк категорий'),
        ),
        migrations.AddField(
            model_name='activitydepartmentcat',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовк категорий'),
        ),
        migrations.AddField(
            model_name='department',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание кафедра'),
        ),
        migrations.AddField(
            model_name='department',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание кафедра'),
        ),
        migrations.AddField(
            model_name='department',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание кафедра'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название кафедры'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название кафедры'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название кафедры'),
        ),
        migrations.AddField(
            model_name='educationalprograms',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание кафедра'),
        ),
        migrations.AddField(
            model_name='educationalprograms',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание кафедра'),
        ),
        migrations.AddField(
            model_name='educationalprograms',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание кафедра'),
        ),
        migrations.AddField(
            model_name='educationalprograms',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название кафедры'),
        ),
        migrations.AddField(
            model_name='educationalprograms',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название кафедры'),
        ),
        migrations.AddField(
            model_name='educationalprograms',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название кафедры'),
        ),
        migrations.AddField(
            model_name='educationalprogramscat',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название Категорий'),
        ),
        migrations.AddField(
            model_name='educationalprogramscat',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название Категорий'),
        ),
        migrations.AddField(
            model_name='educationalprogramscat',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название Категорий'),
        ),
    ]
