# Generated by Django 3.1.6 on 2021-03-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0012_auto_20210211_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydepartment',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок поста'),
        ),
        migrations.AlterField(
            model_name='activitydepartment',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок поста'),
        ),
        migrations.AlterField(
            model_name='activitydepartment',
            name='title_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок поста'),
        ),
        migrations.AlterField(
            model_name='activitydepartment',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок поста'),
        ),
    ]
